name = "MintsML"
uuid = "2494e9a3-49bf-46d5-9870-35f470935b87"
authors = ["John Waczak"]
version = "0.1.0"

[deps]

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
